//
// This code is generated by .github/scripts/update_types_go.sh
// DO NOT EDIT DIRECTLY
//
// types for CodeBuild parameter override. defined to use yaml tags
// https://docs.aws.amazon.com/codebuild/latest/APIReference/API_StartBuild.html
//

package types

// list of Builds
type BuildConfig struct {
	Builds []Build `yaml:"builds"`
}

type Build struct {
	ProjectName                      string                            `yaml:"projectName"`
	SecondarySourcesOverride         []SecondarySourcesOverride        `yaml:"secondarySourcesOverride,omitempty"`
	SecondarySourcesVersionOverride  []SecondarySourcesVersionOverride `yaml:"secondarySourcesVersionOverride,omitempty"`
	SourceVersion                    string                            `yaml:"sourceVersion,omitempty"`
	ArtifactsOverride                ArtifactsOverride                 `yaml:"artifactsOverride,omitempty"`
	SecondaryArtifactsOverride       []SecondaryArtifactsOverride      `yaml:"secondaryArtifactsOverride,omitempty"`
	EnvironmentVariablesOverride     []EnvironmentVariablesOverride    `yaml:"environmentVariablesOverride,omitempty"`
	SourceTypeOverride               string                            `yaml:"sourceTypeOverride,omitempty"`
	SourceLocationOverride           string                            `yaml:"sourceLocationOverride,omitempty"`
	SourceAuthOverride               SourceAuthOverride                `yaml:"sourceAuthOverride,omitempty"`
	GitCloneDepthOverride            int                               `yaml:"gitCloneDepthOverride,omitempty"`
	GitSubmodulesConfigOverride      GitSubmodulesConfigOverride       `yaml:"gitSubmodulesConfigOverride,omitempty"`
	BuildspecOverride                string                            `yaml:"buildspecOverride,omitempty"`
	InsecureSslOverride              bool                              `yaml:"insecureSslOverride,omitempty"`
	ReportBuildStatusOverride        bool                              `yaml:"reportBuildStatusOverride,omitempty"`
	BuildStatusConfigOverride        BuildStatusConfigOverride         `yaml:"buildStatusConfigOverride,omitempty"`
	EnvironmentTypeOverride          string                            `yaml:"environmentTypeOverride,omitempty"`
	ImageOverride                    string                            `yaml:"imageOverride,omitempty"`
	ComputeTypeOverride              string                            `yaml:"computeTypeOverride,omitempty"`
	CertificateOverride              string                            `yaml:"certificateOverride,omitempty"`
	CacheOverride                    CacheOverride                     `yaml:"cacheOverride,omitempty"`
	ServiceRoleOverride              string                            `yaml:"serviceRoleOverride,omitempty"`
	PrivilegedModeOverride           bool                              `yaml:"privilegedModeOverride,omitempty"`
	TimeoutInMinutesOverride         int                               `yaml:"timeoutInMinutesOverride,omitempty"`
	QueuedTimeoutInMinutesOverride   int                               `yaml:"queuedTimeoutInMinutesOverride,omitempty"`
	EncryptionKeyOverride            string                            `yaml:"encryptionKeyOverride,omitempty"`
	IdempotencyToken                 string                            `yaml:"idempotencyToken,omitempty"`
	LogsConfigOverride               LogsConfigOverride                `yaml:"logsConfigOverride,omitempty"`
	RegistryCredentialOverride       RegistryCredentialOverride        `yaml:"registryCredentialOverride,omitempty"`
	ImagePullCredentialsTypeOverride string                            `yaml:"imagePullCredentialsTypeOverride,omitempty"`
	DebugSessionEnabled              bool                              `yaml:"debugSessionEnabled,omitempty"`
	FleetOverride                    FleetOverride                     `yaml:"fleetOverride,omitempty"`
	AutoRetryLimitOverride           int                               `yaml:"autoRetryLimitOverride,omitempty"`
}
type GitSubmodulesConfig struct {
	FetchSubmodules bool `yaml:"fetchSubmodules,omitempty"`
}
type Auth struct {
	Type     string `yaml:"type,omitempty"`
	Resource string `yaml:"resource,omitempty"`
}
type BuildStatusConfig struct {
	Context   string `yaml:"context,omitempty"`
	TargetURL string `yaml:"targetUrl,omitempty"`
}
type SecondarySourcesOverride struct {
	Type                string              `yaml:"type,omitempty"`
	Location            string              `yaml:"location,omitempty"`
	GitCloneDepth       int                 `yaml:"gitCloneDepth,omitempty"`
	GitSubmodulesConfig GitSubmodulesConfig `yaml:"gitSubmodulesConfig,omitempty"`
	Buildspec           string              `yaml:"buildspec,omitempty"`
	Auth                Auth                `yaml:"auth,omitempty"`
	ReportBuildStatus   bool                `yaml:"reportBuildStatus,omitempty"`
	BuildStatusConfig   BuildStatusConfig   `yaml:"buildStatusConfig,omitempty"`
	InsecureSsl         bool                `yaml:"insecureSsl,omitempty"`
	SourceIdentifier    string              `yaml:"sourceIdentifier,omitempty"`
}
type SecondarySourcesVersionOverride struct {
	SourceIdentifier string `yaml:"sourceIdentifier,omitempty"`
	SourceVersion    string `yaml:"sourceVersion,omitempty"`
}
type ArtifactsOverride struct {
	Type                 string `yaml:"type,omitempty"`
	Location             string `yaml:"location,omitempty"`
	Path                 string `yaml:"path,omitempty"`
	NamespaceType        string `yaml:"namespaceType,omitempty"`
	Name                 string `yaml:"name,omitempty"`
	Packaging            string `yaml:"packaging,omitempty"`
	OverrideArtifactName bool   `yaml:"overrideArtifactName,omitempty"`
	EncryptionDisabled   bool   `yaml:"encryptionDisabled,omitempty"`
	ArtifactIdentifier   string `yaml:"artifactIdentifier,omitempty"`
	BucketOwnerAccess    string `yaml:"bucketOwnerAccess,omitempty"`
}
type SecondaryArtifactsOverride struct {
	Type                 string `yaml:"type,omitempty"`
	Location             string `yaml:"location,omitempty"`
	Path                 string `yaml:"path,omitempty"`
	NamespaceType        string `yaml:"namespaceType,omitempty"`
	Name                 string `yaml:"name,omitempty"`
	Packaging            string `yaml:"packaging,omitempty"`
	OverrideArtifactName bool   `yaml:"overrideArtifactName,omitempty"`
	EncryptionDisabled   bool   `yaml:"encryptionDisabled,omitempty"`
	ArtifactIdentifier   string `yaml:"artifactIdentifier,omitempty"`
	BucketOwnerAccess    string `yaml:"bucketOwnerAccess,omitempty"`
}
type EnvironmentVariablesOverride struct {
	Name  string `yaml:"name,omitempty"`
	Value string `yaml:"value,omitempty"`
	Type  string `yaml:"type,omitempty"`
}
type SourceAuthOverride struct {
	Type     string `yaml:"type,omitempty"`
	Resource string `yaml:"resource,omitempty"`
}
type GitSubmodulesConfigOverride struct {
	FetchSubmodules bool `yaml:"fetchSubmodules,omitempty"`
}
type BuildStatusConfigOverride struct {
	Context   string `yaml:"context,omitempty"`
	TargetURL string `yaml:"targetUrl,omitempty"`
}
type CacheOverride struct {
	Type     string   `yaml:"type,omitempty"`
	Location string   `yaml:"location,omitempty"`
	Modes    []string `yaml:"modes,omitempty"`
}
type CloudWatchLogs struct {
	Status     string `yaml:"status,omitempty"`
	GroupName  string `yaml:"groupName,omitempty"`
	StreamName string `yaml:"streamName,omitempty"`
}
type S3Logs struct {
	Status             string `yaml:"status,omitempty"`
	Location           string `yaml:"location,omitempty"`
	EncryptionDisabled bool   `yaml:"encryptionDisabled,omitempty"`
	BucketOwnerAccess  string `yaml:"bucketOwnerAccess,omitempty"`
}
type LogsConfigOverride struct {
	CloudWatchLogs CloudWatchLogs `yaml:"cloudWatchLogs,omitempty"`
	S3Logs         S3Logs         `yaml:"s3Logs,omitempty"`
}
type RegistryCredentialOverride struct {
	Credential         string `yaml:"credential,omitempty"`
	CredentialProvider string `yaml:"credentialProvider,omitempty"`
}
type FleetOverride struct {
	FleetArn string `yaml:"fleetArn,omitempty"`
}
