#!/usr/bin/env bash
set -eu

file_path="internal/types/types.go"

# Write header
header='
//
// This code is generated by .github/scripts/update_types_go.sh
// DO NOT EDIT DIRECTLY
//
// types for CodeBuild parameter override. defined to use yaml tags
// https://docs.aws.amazon.com/codebuild/latest/APIReference/API_StartBuild.html
//

package types

// list of Builds
type BuildConfig struct {
	Builds any `yaml:"builds"`
}
'
echo "$header" > "$file_path"

# Get the latest StartBuildInput Json and convert to Go Struct. Then append to types.go
latest_input=$(docker run --rm -i amazon/aws-cli codebuild start-build --generate-cli-skeleton)
converted=$(echo "$latest_input" | node .github/scripts/json-to-go.js)
echo "$converted" >> "$file_path"
gofumpt -w "$file_path"

# Create PR if the file is updated
if git diff --exit-code "$file_path"; then
    echo "No changes detected"
    exit 0
fi
branch="update-start-build-input-$(date +%Y-%m-%d-%H-%M-%S)"
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git switch -c "$branch"
git add "$file_path"
git commit -m "Update StartBuildInput $(date +%Y-%m-%d)"
git push origin "$branch"
gh pr create --title "Update StartBuildInput $(date +%Y-%m-%d)" \
             --body "This PR is generated by .github/scripts/update_types_go.sh" \
             --fill-verbose
