# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write

jobs:

  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./... -coverprofile=coverage.out

    - name: check coverage
      uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1.5.1
