name: Update StartBuildInput type
on:
  schedule:
    - cron: "0 21 * * 5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: Update StartBuildInput type
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Install tools
        run: go install mvdan.cc/gofumpt@latest

      - name: Updates types.go
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: bash .github/scripts/update_types_go.sh
