name: Update StartBuildInput type
on:
  schedule:
    - cron: "0 21 * * 5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: Update StartBuildInput type
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Install tools
        run: go install mvdan.cc/gofumpt@latest

      - name: Updates types.go
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: bash .github/scripts/update_types_go.sh
